spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:food-ordering-system

  jpa:
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true

logging:
  level:
    root: warn
  org:
    springframework:
      web: debug
    hibernate: error
